version: '3.8'

services:
  postgres:
    image: postgres:14.11
    container_name: postgres
    hostname: postgres_eniqilo
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: "yuyuhuyuhuuya/eniqilo_app:1.0"
    container_name: eniqilo_app
    hostname: eniqilo_app
    ports:
      - "8080:8080"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PARAMS: ${DB_PARAMS}
      JWT_SECRET: ${JWT_SECRET}
      BCRYPT_SALT: ${BCRYPT_SALT}      

volumes:
  postgres_data:
    driver: local
