package global_constant

const SUCCESS = "Success"
const SUCCESS_REGISTER_USER = "User registered successfully"
const SUCCESS_LOGIN_USER = "User logged in successfully"
const SUCCESS_GET_PRODUCT = "Success get product"
const SUCCESS_DELETE_PRODUCT = "Successfully delete product"
const INTERNAL_SERVER_ERROR = "Internal Server Error"
const FAILED_PARSE_REQ_BODY = "Failed to parse request body"
const FAIL_VALIDATE_REQ_BODY = "Failed to validate request body"
const NOT_FOUND = "Not Found"
const WRONG_PASSWORD = "Wrong Password"
const FAIL_GENERATE_TOKEN = "Failed to generate token"
const EXISTING_PHONE_NUMBER = "Phone number already exists"
const PHONE_NUMBER_NOT_FOUND = "Phone number not found"
const FAIL_GET_PRODUCT = "Failed to get product"
const FAIL_DELETE_PRODUCT = "Failed to delete product, id not found"
